config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'nooks#index'
  resources :locations
  resources :reservations do
    collection do
      get :mine
    end
    member do
      patch :cancel
    end
  end

  resources :nooks, except: [:new, :edit, :create, :update, :destroy] do
    member do
      get :reserve
    end
    collection do
      get :search
      post :search
    end
  end

  get 'select_locations', to: 'locations#select', as: :select_locations
  get 'notifications', to: 'users#notifications', as: :user_notifications
  get 'notifications/new', to: 'users#new_notifications', as: :user_new_notifications

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    get 'calendar', to: 'calendar#index'
    get 'welcome', to: 'welcome#index'

    get 'nook_statistics', to: 'nook_statistics#index'
    post 'nook_statistics/fetch', to: 'nook_statistics#fetch', as: :nook_stats_fetch
    post 'nook_statistics/download', to: 'nook_statistics#download', as: :nook_stats_download

    get 'location_statistics', to: 'location_statistics#index'
    post 'location_statistics/fetch', to: 'location_statistics#fetch', as: :location_stats_fetch
    post 'location_statistics/download', to: 'location_statistics#download', as: :location_stats_download

    get 'reservation/:id/approve', to: 'reservations#approve', as: :reservation_approve
    get 'reservation/:id/reject', to: 'reservations#reject', as: :reservation_reject

    get 'nook/check_availability/:reservation_id', to: 'nooks#check_availability', as: :check_availability
    delete 'nooks/:id/photos/:photo_id', to: 'nooks#remove_photo', as: :remove_photo

    root controller: :welcome, action: :index
  end

  match '*a', :to => 'errors#routing', via: :get
end

app/views/shared/_carousel.html.slim
- nook_images = ['placeholder.jpg'] if nook_images.count < 1
div#nook-carousel
  div#nook-carousel-element.carousel.slide data-ride="carousel"
    div.carousel-inner role="listbox"
      - nook_images.each_with_index do |image, i|
        - Rails.logger.debug image
        div class=('item' + (i == 0 ? ' active' : ''))
          = image_tag image

    - if nook_images.count > 1
      a.left.carousel-control href="#nook-carousel-element" role="button" data-slide="prev"
        span.glyphicon.glyphicon-chevron-left aria-hidden="true"
        span.sr-only Previous
      a.right.carousel-control href="#nook-carousel-element" role="button" data-slide="next"
        span.glyphicon.glyphicon-chevron-right aria-hidden="true"
        span.sr-only Next
  - if nook_images.count > 1
    div.carousel-thumbnails
      - nook_images.each_with_index do |image, i|
        div.col-md-2
          a.thumbnail href="#nook-carousel-element" role="button" data-slide-to="#{i}"
            = image_tag image
div.empty-separator

app/views/shared/_modal.html.slim
div.modal-content.col-md-8
  div.modal-body.row.left-row
    = content_for(:modal_left)
div.modal-content.col-md-4
  div.modal-body.row.right-row
    = content_for(:modal_right)

app/views/shared/_modal_onecolumn.html.slim
div class="panel panel-default #{content_for(:modal_class)}"
  div.panel-heading
    h3.panel-title
      = content_for(:modal_title)
  div.panel-body
    = content_for(:modal_content)
  div.panel-footer
    = content_for(:modal_footer)

app/views/shared/_nav_admin_pill.html.slim
   ul.nav.nav-pills.navbar-right
      li.dropdown
        a#user-pill.dropdown-toggle.row data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
          div.col-md-2
            span.glyphicon.glyphicon-certificate
          div.col-md-7
            div.col-md-12 = current_user.try(:full_name) || 'User'
            div.col-md-12 #{current_user.try(:admin?) ? 'Admin' : '' }
          div.col-md-3
            span.glyphicon.glyphicon-menu-hamburger
            span.caret
        ul.dropdown-menu aria-labelledby="user-pill"
          - if user_signed_in?
            li = link_to('Logout', destroy_user_session_path, :method => :delete)
          - else
            li = link_to('Login', new_user_session_path)

app/views/shared/_nav_links.html.slim
ul.nav.nav-pills.navbar-left
  li
    = link_to '#',{ id:"sidebar-toggle"} do
      span.glyphicon.glyphicon-menu-hamburger
    end
  - if active_page?('nooks')
    li role="presentation" data-view="masonry" class="active"
      = link_to '#' do
        span.glyphicon.glyphicon-globe
      end
    li role="presentation" data-view="expanded"
      = link_to '#' do
        span.glyphicon.glyphicon-time
      end
  - else
    li role="presentation"
      = link_to nooks_path do
        span.glyphicon.glyphicon-globe
      end

ul.nav.nav-pills.navbar-right
  - if user_signed_in?
    li
      a href="#{user_new_notifications_path}" class="notify-link"
        span class="badge badge-danger icon-count"
          = current_user.notifications.unseen.length
        span class="glyphicon glyphicon-bell notify-bell"

  li.dropdown
    a#user-pill.dropdown-toggle.row data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
      div.col-xs-2.col-sm-2.col-md-2.col-lg-2
        span.glyphicon.glyphicon-certificate
      div.col-xs-7.col-sm-7.col-md-7.col-lg-7#user-pill-username
        div.col-md-12 = current_user.try(:full_name) || ''
      div.col-xs-3.col-sm-3.col-md-3.col-lg-3
        span.glyphicon.glyphicon-menu-hamburger
        span.caret
    ul.dropdown-menu aria-labelledby="user-pill"
      - if user_signed_in?
        li = link_to('My Reservations', mine_reservations_path)
        li.divider role="separator"
        li = link_to('My Notifications', user_notifications_path)
        li.divider role="separator"
        li = link_to('Logout', destroy_user_session_path, :method => :delete)
      - else
        li = link_to('Login', new_user_session_path)

app/views/shared/_nav_pill.html.slim
    ul.nav.nav-pills.navbar-right
      li.dropdown
        a#user-pill.dropdown-toggle.row data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
          div.col-xs-2.col-sm-2.col-md-2.col-lg-2
            span.glyphicon.glyphicon-certificate
          div.col-xs-7.col-sm-7.col-md-7.col-lg-7#user-pill-username
            div.col-md-12 = current_user.try(:full_name) || ''
          div.col-xs-3.col-sm-3.col-md-3.col-lg-3
            span.glyphicon.glyphicon-menu-hamburger
            span.caret
        ul.dropdown-menu aria-labelledby="user-pill"
          - if user_signed_in?
            li = link_to('My Reservations', mine_reservations_path)
            li.divider role="separator"
            li = link_to('Logout', destroy_user_session_path, :method => :delete)
          - else
            li = link_to('Login', new_user_session_path)

app/views/shared/_nook_reservations.html.slim
- upcoming = nook.reservations.where('start_time > ?', DateTime.now).limit(10).order('start_time asc')
- if upcoming.empty?
  div.upcoming-reservation.clearfix
    = t('reservations.no_reservations')
- else
  - upcoming.each_with_index do |reservation, i|
    div.upcoming-reservation.clearfix
      - if ((i - 1) < 0 || (upcoming[i - 1].start.strftime('%d') != reservation.start.strftime('%d')))
        div.upcoming-reservation-day
          = reservation.start.strftime('%B')
          = ' '
          = reservation.start.strftime('%d')
          - if reservation.start.today?
            = ' - '
            = t('reservations.today')
          - if reservation.start.to_date == Date.tomorrow
            = ' - '
            = t('reservations.tomorrow')
      div.upcoming-reservation-user.col-sm-6
        = reservation.requester.email
      div.upcoming-reservation-range.col-sm-6.text-right
        = reservation.start.strftime('%I:%M%p')
        = '-'
        = reservation.end.strftime('%I:%M%p')
      - if (!upcoming[i + 1].nil? && upcoming[i + 1].start.strftime('%d') != reservation.start.strftime('%d'))
        div.empty-separator

app/views/shared/_plain_time_select.html.slim
div.time-select
  - hour_counter = 0
  - (0..1).each do |half|
    div.col-sm-6
      - (0..11).each do |hour|
        div.time-slot.col-sm-1
          button.btn.open type="button" value="#{hour_counter.to_s.rjust(2, '0')}00"
          button.btn.open.right type="button" value="#{hour_counter.to_s.rjust(2, '0')}30"
          - if show_hours and hour_counter.even?
            - if half == 0
              span.small = "#{hour_counter == 0 ? 12 : hour_counter}:00AM"
            - else          
              span.small = "#{hour_counter == 12 ? hour_counter : hour_counter - 12}:00PM"
        - hour_counter += 1

app/views/shared/_rating_tag.html.slim
div
  span #{rating_label}:
  span &#9733;
  span &#9733;
  span &#9733;
  span &#9733;
  span &#9733;

app/views/shared/_time_select.html.slim
- unselectable = false unless defined? unselectable
div.time-select class=("unselectable" if unselectable)
  - disabled = false
  - hour_counter = 0
  - schedule.each do |half_day|
    div.col-sm-6
      - half_day.each_with_index do |chunk, chunk_i|
        - disabled = !chunk[0]
        - size = (chunk[1] - chunk[1] % 2) / 2
        - (0..size-1).each do |hour|
          div.time-slot.col-sm-1
            - if disabled
              button.btn.taken type="button" disabled='true' value="#{hour_counter.to_s.rjust(2, '0')}00"
              button.btn.taken type="button" disabled='true' value="#{hour_counter.to_s.rjust(2, '0')}30"
            - else
              button.btn.open type="button" value="#{hour_counter.to_s.rjust(2, '0')}00"
              button.btn.open.right type="button" value="#{hour_counter.to_s.rjust(2, '0')}30"
            - if show_hours and hour_counter.even?
              - if hour_counter < 12
                span.small = "#{hour_counter == 0 ? 12 : hour_counter}:00AM"
              -else
                span.small = "#{hour_counter == 12 ? hour_counter : hour_counter - 12}:00PM"
          - hour_counter += 1

        - if chunk[1] % 2 == 1 and chunk_i + 1 < half_day.length
          - half_day[chunk_i + 1][1] = half_day[chunk_i + 1][1] - 1
          div.time-slot.col-sm-1
            - if disabled
              button.btn.taken type="button" disabled='true' value="#{hour_counter.to_s.rjust(2, '0')}00"
              button.btn.open.right type="button" value="#{hour_counter.to_s.rjust(2, '0')}30"
            - else
              button.btn.open type="button" value="#{hour_counter.to_s.rjust(2, '0')}00"
              button.btn.taken.right type="button" disabled='true' value="#{hour_counter.to_s.rjust(2, '0')}30"
            - if show_hours and hour_counter.even?
              - if hour_counter < 12
                span.small = "#{hour_counter == 0 ? 12 : hour_counter}:00AM"
              -else
                span.small = "#{hour_counter == 12 ? hour_counter : hour_counter - 12}:00PM"
          - hour_counter += 1