config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'nooks#index'
  resources :locations
  resources :reservations do
    collection do
      get :mine
    end
    member do
      patch :cancel
    end
  end

  resources :nooks, except: [:new, :edit, :create, :update, :destroy] do
    member do
      get :reserve
    end
    collection do
      get :search
      post :search
    end
  end

  get 'select_locations', to: 'locations#select', as: :select_locations
  get 'notifications', to: 'users#notifications', as: :user_notifications
  get 'notifications/new', to: 'users#new_notifications', as: :user_new_notifications

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    get 'calendar', to: 'calendar#index'
    get 'welcome', to: 'welcome#index'

    get 'nook_statistics', to: 'nook_statistics#index'
    post 'nook_statistics/fetch', to: 'nook_statistics#fetch', as: :nook_stats_fetch
    post 'nook_statistics/download', to: 'nook_statistics#download', as: :nook_stats_download

    get 'location_statistics', to: 'location_statistics#index'
    post 'location_statistics/fetch', to: 'location_statistics#fetch', as: :location_stats_fetch
    post 'location_statistics/download', to: 'location_statistics#download', as: :location_stats_download

    get 'reservation/:id/approve', to: 'reservations#approve', as: :reservation_approve
    get 'reservation/:id/reject', to: 'reservations#reject', as: :reservation_reject

    get 'nook/check_availability/:reservation_id', to: 'nooks#check_availability', as: :check_availability
    delete 'nooks/:id/photos/:photo_id', to: 'nooks#remove_photo', as: :remove_photo

    root controller: :welcome, action: :index
  end

  match '*a', :to => 'errors#routing', via: :get
end

app/models/nook.rb
require 'carrierwave/orm/activerecord'

class Nook < ActiveRecord::Base
  include ExtensibleAttrs
  include OpenAtHours

  belongs_to :location
  has_many :reservations, dependent: :destroy

  delegate :name, :attrs, to: :location, prefix: true, allow_nil: true

  acts_as_taggable_on :amenities

  validates_presence_of :name, :location_id
  # schedulable and reservation_length are both in seconds
  validates_numericality_of :min_capacity, :min_schedulable,
    :min_reservation_length, greater_than_or_equal_to: 0, allow_blank: true
  validates_numericality_of :min_capacity, :max_capacity, only_integer: true,
    allow_blank: true
  validates_inclusion_of :bookable, :repeatable, :requires_approval,
    in: [true, false]

  before_validation :set_defaults
  after_initialize :set_defaults

  mount_uploaders :photos, PhotoUploader

  STATUSES = [ :available, :unavailable ]

  # CarrierWave is throwing errors without it
  skip_callback :commit, :after, :remove_previously_stored_photos

  def available_now?
    available_at? Time.now
  end

  def available_at?(time)
    available = bookable && reservations.happening_at(time).empty?
    available &&= location.open_at?(time) if location.open_schedule
    available &&= open_at?(time) if open_schedule
    available
  end

  def available_for?(time_range,res=nil)
    available = bookable && reservations.overlapping_with(time_range,res).empty?
    available &&= location.open_for_range?(time_range) if location.open_schedule
    available &&= open_for_range?(time_range) if open_schedule
    available # I don't think this line is necessary, but not sure yet.
  end

  # used in blocking reserved slots on reservation form or expanded-nook view
  def reserved_slots(date)
    Reservation.confirmed.where(nook_id: self.id)
                          .happening_within(date.in_time_zone.beginning_of_day..date.in_time_zone.end_of_day)
                          .map do |r|
                            r.start.strftime('%H%M').to_i..
                            (r.end + 1.seconds).strftime('%H%M').to_i
                          end
  end

  def remove_photo(photo_id)
    remain_photos = self.photos # copy the array
    deleted_photo = remain_photos.delete_at(photo_id.to_i) # delete the target photo
    deleted_photo.try(:remove!) # delete photo from S3
    self.photos = remain_photos # re-assign back
    self.remove_photos! if remain_photos.empty?
    if self.save
      return true
    else
      return false
    end
  end
  # Used in initializing selectize options
  def self.strip_nook_data(nooks)
    nooks = nooks.map do |nook|
      [ nook.id, nook.name ].join(':')
    end
    nooks.join(',')
  end

  private

  def set_defaults
    self.attrs ||= {}
    self.hidden_attrs ||= {}
    self.bookable ||= true if bookable.nil?
    self.requires_approval ||= true if requires_approval.nil?
    self.repeatable ||= false if repeatable.nil?
    self.open_schedule ||= location.open_schedule.dup if location
  end

  def self.inheritance_column
    :sti_type
  end
end

app/controllers/admin/nooks_controller.rb
module Admin
  class NooksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Nook.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Nook.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information

    def new
      resource = resource_class.new
      resource.open_schedule = OpenSchedule.new
      resource.open_schedule.add_9_to_5

      render locals: {
        page: Administrate::Page::Form.new(dashboard, resource),
      }
    end

    def create
      create_params = resource_params
      create_params.delete(:amenities)
      create_params.delete(:open_schedule)
      resource = resource_class.new(create_params)

      if resource.save
        resource.amenity_list = params[:nook][:amenities]
        if params[:copy_location_schedule]
          resource.open_schedule = resource.location.open_schedule.dup
        else
          resource.open_schedule.blocks = params[:nook][:open_schedule]
          resource.open_schedule.save
        end
        resource.save

        redirect_to(
          [namespace, resource],
          notice: translate_with_resource("create.success"),
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource),
        }
      end
    end

    def index
      search_term = params[:search].to_s.strip
      resources = Administrate::Search.new(resource_resolver, search_term).run
      unless current_user.superadmin?
        locations = Location.with_roles(:admin, current_user)
        resources = resources.where(location_id: locations.ids)
      end
      resources = order.apply(resources)
      resources = resources.page(params[:page]).per(records_per_page)
      page = Administrate::Page::Collection.new(dashboard, order: order)

      render locals: {
        resources: resources,
        search_term: search_term,
        page: page,
      }
    end

    def update
      update_params = resource_params
      update_params.delete(:amenities)
      update_params.delete(:open_schedule)
      update_params.delete(:photos)
      if requested_resource.update(update_params)
        requested_resource.amenity_list = params[:nook][:amenities]
        requested_resource.open_schedule.blocks = params[:nook][:open_schedule]
        photos = requested_resource.photos
        photos += (params[:nook][:photos] || [])
        requested_resource.photos = photos
        requested_resource.open_schedule.save
        requested_resource.save
        redirect_to(
          [namespace, requested_resource],
          notice: translate_with_resource("update.success"),
        )
      else
        render :edit, locals: {
          page: Administrate::Page::Form.new(dashboard, requested_resource),
        }
      end
    end

    def check_availability
      reservation_id = params[:reservation_id]
      @reservation = Reservation.where(id: reservation_id).first
      @available = nil
      unless @reservation.nil?
        @available = @reservation.nook.available_for?(@reservation.start..@reservation.end,@reservation)
      end
      render :js, template: 'admin/nooks/availability'
    end

    def remove_photo
      res = requested_resource.remove_photo(params[:photo_id]) # delete the target photo
      flash[:error] = "Failed deleting photo" if res == false
      redirect_to :back
    end
  end
end

app/controllers/nooks_controller.rb
class NooksController < ApplicationController
  before_action :set_nook, only: [:show, :reserve]
  before_action :authenticate_user!, only: [:reserve]

  helper_method :locations, :types, :amenities, :available_now

  layout false, only: [:edit]

  # GET /nooks
  # GET /nooks.json
  def index
    @nooks = []#Nook.order(:id)
  end

  # GET /nooks/1
  # GET /nooks/1.json
  def show
    respond_to do |format|
      format.json
      format.html { render @nook, layout: false if request.xhr? }
    end
  end

  def search
    @search = NookSearch.new(params)
    @nooks = @search.results.sort_by(&:id)

    date = params[:days][0].to_date
    day = date.wday
    @date_range = ( (date - day)..(date + (6 - day)) )
    @search_date = date

    respond_to do |format|
      format.json
      format.html { render 'search', layout: false if request.xhr? }
    end
  end

  def reserve
    @reservation = Reservation.new
    @reservation.nook = @nook

    unless params[:search_date].nil?
      @search_date = params[:search_date].to_date
    end

    respond_to do |format|
      format.json
      format.html {
        render partial: 'nooks/nook', locals: { nook: @nook }, layout: false if request.xhr?
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nook
      @nook = Nook.find(params[:id])
    end

    def locations
      @locations ||= Location.all
    end

    def types
      @types ||= @nooks.collect(&:type).uniq
    end

    def amenities
      @amenities ||= (@nooks || @nook.location.try(:nooks) || Nook.all).collect(&:amenities).flatten.uniq
    end
end

app/helpers/admin/nooks_helper.rb
module Admin::NooksHelper
end

app/helpers/nooks_helper.rb
module NooksHelper
  def nook_capacity
    min = Nook.minimum(:min_capacity)
    if min == nil || Nook.where(min_capacity: nil).count > 0
      min = 0
    end
    array = ( min..(Nook.maximum(:max_capacity) || (min + 1) ) ).to_a
    unless array.include?(0)
      array = [0] + array
    end
    return array.map{ |x| x > 0 ? [x, x] : [x, "Any"] }.to_h
  end
end

app/views/nooks/_admin_main.html.slim
- content_for(:main_menu) do
  div
    = render 'layouts/admin'

    p.notice = notice
    p.alert = alert

  - #TODO: Replace this placeholder conditional.
  = render current_user.try(:admin?) ? 'admin_filters' : 'booking_filters'

  = link_to 'Edit global attributes', '#'

  table.table
    thead
      tr
        th
          = t('nooks.filters.nook_name').singularize
          span.caret
        th
          = t('nooks.filters.locations').singularize
          span.caret
        th
          = t('nooks.filters.types').singularize
          span.caret
        th
          = t('nooks.filters.statuses').singularize
          span.caret
        th
          = t('nooks.filters.capacity')
          span.caret
        th colspan="2"

    tbody
      - @nooks.each do |nook|
        tr
          td = link_to nook.name, nook, class: 'remote-modal', data: { modal: '#modal' }
          td = link_to nook.location.name, nook.location if nook.location
          td = nook.type
          td = nook.available_now?
          td = nook.max_capacity
          td = link_to 'Edit', edit_nook_path(nook), class: 'remote-modal', data: { modal: '#modal' }
          td = link_to 'Destroy', nook, method: :delete, data: { confirm: 'Are you sure?' }

  <br>

  = link_to 'New Nook', new_nook_path, class: 'btn btn-primary remote-modal', data: { modal: '#modal' }

app/views/nooks/_booking_filters.html.slim
- content_for(:left_menu) do
  - content_for(:left_menu_classes) { 'booking' }
  - content_for(:body_classes) { 'booking' }
  form#left_menu.booking
    div#location-filter.btn-group-sm.filter
      div.filter-title 1. #{t('nooks.filters.where')}
      = select_tag "Locations", options_from_collection_for_select(Location.all, "id", "name", Location.all.map(&:id) ), multiple: true, width: "100%", id: "location-element"
      = button_tag "Clear Locations", id:"clear-select"

    div.filter.date.this-week
      div.filter-title 2. #{t('nooks.filters.when')}
      div.date-future
        div#datepicker-element
        div.row
          div.col-md-12
            div.input-group
              span.input-group-addon = "From"
              <input type='text' class="form-control" id='timeStart' value="Any">

          br
          br
          div.col-md-12
            div.input-group
              span.input-group-addon = "Up to"
              <input type='text' class="form-control" id='timeEnd' value="Any">
    div#location-filter.btn-group-sm.filter
      div.filter-title 3. #{t('nooks.filters.capacity')}
      = select_tag :nook_capacity, options_from_collection_for_select(nook_capacity, :first, :last), width: "100%"

    div#filtered-results.filter

app/views/nooks/_booking_main.html.slim
- content_for(:left_menu)
  = render 'booking_filters'

div.nooks.col-xs-12

app/views/nooks/_nook.html.slim
- content_for(:modal_left) do
  div class="panel panel-default"
    div.panel-heading
      h3.panel-title
        span #{t('nooks.book_this_nook')}
        span.pull-right.nook-title #{nook.name}
    div.panel-body
      = render partial: 'reservations/form', locals: {nook: nook, reservation: @reservation }
  div class="panel panel-default"
    div.panel-heading
      h3.panel-title #{nook.name} #{t('nooks.profile')}
    div.panel-body
      = render 'shared/carousel', :nook_images => nook.photos
      div.description #{nook.description}
      div.empty-separator
      div #{t('nooks.location')}: #{nook.location_name}
      div #{t('nooks.room_type')}: #{nook.type}
      div
        div.nook-map id="nook-#{nook.id}-map" data-latitude='#{nook.location.lat}' data-longitude='#{nook.location.lng}'
        a.nook-map-toggle.toggle-link.pull-right
          = 'Show map '
          span.glyphicon.glyphicon-chevron-down

        javascript:
          // handler and marker both used as global variables
          // they are used in resizing the map after toggling
          handler = Gmaps.build('Google');
          var mapBody = $('#nook-#{nook.id}-map');
          handler.buildMap({
            provider: {},
            internal: { id: 'nook-#{nook.id}-map' }
          }, function() {
            var lat =  mapBody.attr('data-latitude');
            var lng =  mapBody.attr('data-longitude');

            marker = handler.addMarker({
              "lat": lat,
              "lng": lng
            });

            google.maps.event.trigger(handler.getMap(), 'resize');
            handler.map.centerOn(marker);
            handler.getMap().setZoom(17);
          });

- content_for(:modal_right) do
  //= render 'nooks/nook_attributes', nook: nook, amenties: amenities

  - if current_user.superadmin? or current_user.has_role? :admin, nook.location
    div class="panel panel-default"
      div.panel-heading
        h3.panel-title #{t('nooks.upcoming')}
      div.panel-body
        = render 'shared/nook_reservations', nook: nook

= render 'shared/modal'

app/views/nooks/_nook_attributes.html.slim
div class="panel panel-default"
  div.panel-heading
    h3.panel-title #{t('nooks.room_attributes')}
  div.panel-body
    - amenities.each do |amenity|
      div.amenity
        = check_box_tag '', '', amenity.in?(nook.amenities), disabled: true
        = label_tag '' do
          span.blue
          = amenity.name.downcase
      div
    div.empty-separator
    span #{t('nooks.capacity')}:
    = ' '
    span #{[nook.min_capacity.to_i, 1].max}-#{nook.max_capacity}
    div.empty-separator
    = render partial: 'shared/rating_tag', locals: {rating_label: 'Noise Level'}
    = render partial: 'shared/rating_tag', locals: {rating_label: 'Sunlight'}
    = render partial: 'shared/rating_tag', locals: {rating_label: 'Outlets'}

app/views/nooks/_search_expanded.html.slim
input id="nook-reservation-date" type="text" hidden="true" value="#{@search_date}"
input id="nook-reservation-start" type="text" hidden="true"
input id="nook-reservation-end" type="text" hidden="true"

div.col-sm-10.col-sm-offset-1
  div.row
    - nooks.first(4).flatten.each do |nook|
      div.col-md-3 style="padding-left:5px; padding-right:5px;" data-nook=nook.id
        div.nook
          = image_tag nook.photos.first ? nook.photos.first.thumb : 'placeholder.jpg', height: "100%", width: "100%"

          div.nook-property
            span.nook-icon.name
            = nook.name
          div.nook-property
            span.nook-icon.location
            = nook.location_name

  h1
    = @search_date.strftime("%A") + ", "
    = @search_date.strftime("%B %_d") + " "
    small = @search_date.strftime("%Y")

  div.row. style="margin: 10px 0px;"
    div.timeline.col-sm-6
      div.row
        div.col-sm-1
          span.small 12am
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 2am
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 4am
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 6am
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 8am
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 10am
        div.col-sm-1
          span.small

    div.timeline.col-sm-6 style="margin-left: -1px;"
      div.row
        div.col-sm-1
          span.small 12pm
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 2pm
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 4pm
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 6pm
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 8pm
        div.col-sm-1
          span.small
        div.col-sm-1
          span.small 10pm
        div.col-sm-1
          span.small

  div.day
    - nooks.first(4).flatten.each do |nook|
      div.event.col-sm-12.reservation-when-times-2 id="nook--#{nook.id}" data-reserved-slots=nook.reserved_slots(@search_date)
        = render 'shared/time_select', show_hours: false,
                  unselectable: true,
                  schedule: OpenSchedule.advance(nook.open_schedule, (Time.zone.utc_offset.to_f/1.hour - @old_time_zone.now.utc_offset.to_f/1.hour)).spans_chunk(2)[@search_date.wday],
                  reserved_slots: nook.reserved_slots(@search_date)
  div.book
    - nooks.first(4).flatten.each do |nook|
      div id="book--#{nook.id}" style="display:none"
        = link_to reserve_nook_path(id: nook, search_date: @search_date),
          class: 'remote-modal book-this-nook btn btn-primary pull-right', data: {modal: '#modal', callback: 'bookModalLoaded'}
          ="Reserve"

javascript:
  var timeSelectors = {}
  var lastSelectedDay = -1;

  initializeTimeSelectors()
  initializeNookDayline()

app/views/nooks/_search_masonry.html.slim
div.nooks-masonry
- nooks.flatten.each.with_index do |nook, i|
  div.nook-item
    = link_to reserve_nook_path(id: nook, search_date: @search_date),
      class: 'remote-modal book-this-nook', data: {modal: '#modal', callback: 'bookModalLoaded'}
      div.nook
        = image_tag nook.photos.first ? nook.photos.first.thumb : 'placeholder.jpg'
        div.nook-property
          span.nook-icon.name
          = nook.name
        div.nook-property
          span.nook-icon.location
          = nook.location_name
        div class="nook-property availability #{nook.available_now? ? 'available-now' : ''}"
          span.nook-icon.availability
          = nook.available_now? ? t('nooks.available_now') : t('nooks.not_available_now')
        div.nook-property
          span.nook-icon.amenities
          = nook.amenities.join(', ')
        div.nook-property
          span.nook-icon.maxcapacity
          = nook.max_capacity
          = ' '
          = "people".pluralize(nook.max_capacity)

app/views/nooks/index.html.slim
= render 'booking_main'

app/views/nooks/search.html.slim
div.nooks-masonry style="display:none;"
  = render partial: 'nooks/search_masonry', locals: { nooks: @nooks }
div.nooks-expanded style="display:none;"
  = render partial: 'nooks/search_expanded', locals: { nooks: @nooks }

  template.amenities_template
    h3 style="padding-top:0" = "Filter By:"
    div.filter-title = "Amenities"
    - @nooks.collect(&:amenities).flatten.uniq.each do |amenity|
      div.amenity
        = check_box_tag amenity.name, amenity.name, @search.amenities.include?(amenity.name.downcase)
        = label_tag amenity do
          span
          = amenity.name.downcase
    div.filter-title = "Room Types"
    - @nooks.collect(&:type).flatten.uniq.each do |key|
      div#matching-types-list
        = check_box_tag key, key, @search.nook_types.include?(key)
        = label_tag key do
          span
          = key.titleize.pluralize

javascript:
  $('.nooks-' + currentView()).show();
  $('div#filtered-results.filter').html($('.amenities_template').html());
  $('form.booking #filtered-results input').on('change', function () {
    NProgress.start();

    $(document).trigger('filter-updated');
  });