config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'nooks#index'
  resources :locations
  resources :reservations do
    collection do
      get :mine
    end
    member do
      patch :cancel
    end
  end

  resources :nooks, except: [:new, :edit, :create, :update, :destroy] do
    member do
      get :reserve
    end
    collection do
      get :search
      post :search
    end
  end

  get 'select_locations', to: 'locations#select', as: :select_locations
  get 'notifications', to: 'users#notifications', as: :user_notifications
  get 'notifications/new', to: 'users#new_notifications', as: :user_new_notifications

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    get 'calendar', to: 'calendar#index'
    get 'welcome', to: 'welcome#index'

    get 'nook_statistics', to: 'nook_statistics#index'
    post 'nook_statistics/fetch', to: 'nook_statistics#fetch', as: :nook_stats_fetch
    post 'nook_statistics/download', to: 'nook_statistics#download', as: :nook_stats_download

    get 'location_statistics', to: 'location_statistics#index'
    post 'location_statistics/fetch', to: 'location_statistics#fetch', as: :location_stats_fetch
    post 'location_statistics/download', to: 'location_statistics#download', as: :location_stats_download

    get 'reservation/:id/approve', to: 'reservations#approve', as: :reservation_approve
    get 'reservation/:id/reject', to: 'reservations#reject', as: :reservation_reject

    get 'nook/check_availability/:reservation_id', to: 'nooks#check_availability', as: :check_availability
    delete 'nooks/:id/photos/:photo_id', to: 'nooks#remove_photo', as: :remove_photo

    root controller: :welcome, action: :index
  end

  match '*a', :to => 'errors#routing', via: :get
end

app/views/fields/carrierwave_field/_form.html.erb
<%= f.label field.attribute %>
<%- f.object.photos.each_with_index do |photo, index| #grab the index %>
<div>
    <%= image_tag(photo.url) %>
    <%= link_to "Delete",  admin_remove_photo_path(f.object,index), :method => :delete, data: { confirm: "Are you sure you want to delete this image?" } %>
</div>
<% end %>
<div class="field">
  <%= f.file_field field.attribute, multiple: true %>
</div>

app/views/fields/carrierwave_field/_index.html.erb
<% field.thumbnails.each do |url| %>
  <%= image_tag url %>
<% end %>

app/views/fields/carrierwave_field/_show.html.erb
<% field.urls.each do |url| %>
  <%= image_tag url %>
<% end %>